# Generated by Django 6.1.1 on 2026-09-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_hotel_itineraryday_transportitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='final_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
