# Generated by Django 6.1.1 on 2026-09-20 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_quotation_final_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo_library/')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='flight_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='mattress_preference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='nights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='package_tier',
            field=models.CharField(blank=True, choices=[('Luxury', 'Luxury'), ('Luxury+', 'Luxury+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='markup_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='FerryLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_island', models.CharField(max_length=255)),
                ('to_island', models.CharField(max_length=255)),
                ('ferry_operator', models.CharField(max_length=255)),
                ('ferry_class', models.CharField(max_length=100)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='IslandStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island_name', models.CharField(max_length=255)),
                ('stay_order', models.IntegerField()),
                ('nights', models.IntegerField()),
                ('hotel_name', models.CharField(max_length=255)),
                ('room_category', models.CharField(max_length=255)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('day_title', models.CharField(max_length=255)),
                ('morning_text', models.TextField(blank=True)),
                ('afternoon_text', models.TextField(blank=True)),
                ('evening_text', models.TextField(blank=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quotation')),
                ('photos', models.ManyToManyField(blank=True, to='core.photolibrary')),
            ],
        ),
    ]
