# Generated by Django 6.1.1 on 2026-09-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_photolibrary_quotation_adults_quotation_arrival_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.photolibrary'),
        ),
        migrations.CreateModel(
            name='AgencySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='agency/')),
                ('tagline', models.CharField(max_length=255)),
                ('closing_message', models.TextField()),
                ('important_info', models.TextField()),
                ('inclusions', models.TextField()),
                ('exclusions', models.TextField()),
                ('payment_terms', models.TextField()),
                ('contact_phone', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=100)),
                ('closing_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.photolibrary')),
            ],
        ),
    ]
