# Generated by Django 6.1.1 on 2026-10-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activityrate_experience_quotation_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysettings',
            name='agency_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='founder_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='special_inclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agencysettings',
            name='welcome_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='break_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_break_photos', to='core.photolibrary'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='persons_with_mattress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='persons_without_mattress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
