# Generated by Django 6.1.1 on 2026-10-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agencysettings_agency_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
