# Generated by Django 6.1.1 on 2026-10-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_quotation_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
